apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-exz4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-exz4
    app.kubernetes.io/part-of: tkrw-pr712-0075-0062-app
  name: devfile-sample-exz4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-exz4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-exz4
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0062-tenant/tkrw-pr712-0075-0062-app/devfile-sample-exz4@sha256:c07215bbe9ddcb838508fe29671629f212b034c2564a707260eb00d3d7e04e66
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
